#!/bin/sh
# mac-ssh-askpass v1.0.0 - Asks for passphrases in the GUI on macOS.
# Odin Kroeger, 2018
#
# This is free software released into the public domain.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
# MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
# IN NO EVENT SHALL THE AUTHORS BE LIABLE FOR ANY CLAIM, DAMAGES OR
# OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
# ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
# OTHER DEALINGS IN THE SOFTWARE.

CPID=$PPID
CCOMM=$(ps -o comm=, $CPID)

exec osascript - "$@" <<EOF
on run argv
    set text item delimiters to " "
    set prompt to argv as text
    set reply to display dialog prompt ¬
        default answer "" with title "$CCOMM ($CPID)" with hidden answer
    set pass to text returned of reply
    return pass
end run
EOF
